"""Annex III high-risk AI use case areas — machine-readable knowledge pack.

Source of truth: eu-ai-act/references/risk-classification.md (Annex III section)
and eu-ai-act/references/obligations-high-risk.md (obligation articles).

Each AnnexIIIEntry represents one Annex III sub-point.  All downstream
components (classifier, detector, rules, mapping) import from this module
so that extending/updating coverage requires editing only here.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AnnexIIIEntry:
    area: int
    area_name: str
    subpoint: str
    title: str
    obligation_articles: tuple[str, ...]
    conformity_path: str  # "self_assessment" | "notified_body_optional"
    keywords: tuple[str, ...]
    code_signals: tuple[str, ...]
    excludes: tuple[str, ...]
    art6_3_profiling: bool = False
    # True when the regulation text scopes this sub-point to natural persons
    # specifically (e.g. "creditworthiness of natural persons", Annex III 5(b)).
    # For these entries a keyword/code-signal match alone is not sufficient —
    # the scanner must also find evidence the *subject being scored* is a
    # person, not a product, portfolio, or commercial counterparty. Areas that
    # regulate a system/context rather than a person-scoring decision (e.g.
    # biometrics, critical infrastructure, judicial research) are not gated.
    subject_gated: bool = False


ANNEX_III: list[AnnexIIIEntry] = [
    # ── Area 1 — Biometrics ──────────────────────────────────────────────────
    AnnexIIIEntry(
        area=1,
        area_name="biometrics",
        subpoint="1(a)",
        title="Remote biometric identification systems",
        obligation_articles=(
            "Art.6(2)+Annex III pt.1(a)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.11 technical documentation",
            "Art.12 logging",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.15 accuracy/robustness",
            "Art.43 conformity (notified body optional)",
            "Art.49 EU DB registration",
        ),
        conformity_path="notified_body_optional",
        keywords=(
            "remote biometric identification",
            "facial recognition",
            "face recognition",
            "biometric recognition",
            "identity verification at scale",
            "biometric surveillance",
            "gait recognition",
            "voice biometrics identification",
            "iris recognition",
        ),
        code_signals=(
            "face_recognition",
            "facial_recognition",
            "biometric_identify",
            "identify_face",
            "face_match",
            "face_verify",
            "deepface",
            "arcface",
            "insightface",
            "facenet",
            "dlib.face_recognition",
            "recognize_face",
            "biometric_id",
            "remote_biometric",
        ),
        excludes=("personal identity verification by the user themselves",),
        art6_3_profiling=True,
    ),
    AnnexIIIEntry(
        area=1,
        area_name="biometrics",
        subpoint="1(b)",
        title="Biometric categorization inferring sensitive attributes",
        obligation_articles=(
            "Art.6(2)+Annex III pt.1(b)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (notified body optional)",
            "Art.49 EU DB registration",
        ),
        conformity_path="notified_body_optional",
        keywords=(
            "biometric categorization",
            "biometric classification",
            "sensitive attribute inference",
            "race detection from biometrics",
            "political opinion inference",
            "religious belief inference from face",
            "sexual orientation inference",
            "trade union membership inference",
        ),
        code_signals=(
            "biometric_categorize",
            "categorize_biometric",
            "infer_race",
            "infer_gender",
            "infer_religion",
            "predict_ethnicity",
            "sensitive_attribute",
            "facial_attribute",
        ),
        excludes=(
            "labeling/filtering of lawfully acquired biometric datasets in law enforcement",
        ),
        art6_3_profiling=True,
    ),
    AnnexIIIEntry(
        area=1,
        area_name="biometrics",
        subpoint="1(c)",
        title="Emotion recognition systems",
        obligation_articles=(
            "Art.6(2)+Annex III pt.1(c)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (notified body optional)",
            "Art.49 EU DB registration",
        ),
        conformity_path="notified_body_optional",
        keywords=(
            "emotion recognition",
            "emotion detection",
            "affect recognition",
            "sentiment detection from face",
            "facial action unit",
            "valence arousal",
            "mood detection",
            "micro-expression detection",
        ),
        code_signals=(
            "emotion_recognition",
            "detect_emotion",
            "predict_emotion",
            "facial_expression",
            "action_unit",
            "fer",
            "deepface.analyze",
            "affectnet",
            "emotic",
            "valence",
            "arousal",
        ),
        excludes=("medical or safety purposes",),
    ),
    # ── Area 2 — Critical Infrastructure ────────────────────────────────────
    AnnexIIIEntry(
        area=2,
        area_name="critical_infrastructure",
        subpoint="2",
        title="Safety components of critical infrastructure management",
        obligation_articles=(
            "Art.6(2)+Annex III pt.2",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.11 technical documentation",
            "Art.12 logging",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.15 accuracy/robustness",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "road traffic management",
            "traffic control AI",
            "water supply management AI",
            "gas supply safety AI",
            "heating supply AI",
            "electricity grid AI",
            "power grid safety",
            "critical digital infrastructure",
            "SCADA AI",
            "industrial control system AI",
        ),
        code_signals=(
            "traffic_control",
            "grid_management",
            "scada",
            "power_grid",
            "water_treatment",
            "gas_pipeline",
            "critical_infrastructure",
            "safety_critical",
            "plc_control",
            "industrial_control",
        ),
        excludes=(),
    ),
    # ── Area 3 — Education ───────────────────────────────────────────────────
    AnnexIIIEntry(
        area=3,
        area_name="education",
        subpoint="3(a)",
        title="Determining access or admission to educational institutions",
        obligation_articles=(
            "Art.6(2)+Annex III pt.3(a)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "university admission AI",
            "school admission system",
            "student selection algorithm",
            "enrollment decision AI",
            "academic admission scoring",
            "college application ranking",
        ),
        code_signals=(
            "admission_score",
            "predict_admission",
            "enrollment_decision",
            "student_selection",
            "application_rank",
            "admit_student",
            "reject_application",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=3,
        area_name="education",
        subpoint="3(b)",
        title="Evaluating learning outcomes materially influencing the learning process",
        obligation_articles=(
            "Art.6(2)+Annex III pt.3(b)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "automated grading",
            "AI grading system",
            "essay scoring AI",
            "learning outcome assessment",
            "automated assessment",
            "intelligent tutoring grade",
        ),
        code_signals=(
            "grade_essay",
            "auto_grade",
            "automated_grading",
            "score_assignment",
            "learning_outcome",
            "predict_grade",
        ),
        excludes=(),
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=3,
        area_name="education",
        subpoint="3(c)",
        title="Assessing appropriate level of education received",
        obligation_articles=(
            "Art.6(2)+Annex III pt.3(c)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "education level assessment",
            "curriculum placement AI",
            "learning path recommendation AI",
            "student level classification",
        ),
        code_signals=(
            "education_level",
            "curriculum_placement",
            "learning_path",
            "student_level",
            "classify_student",
        ),
        excludes=(),
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=3,
        area_name="education",
        subpoint="3(d)",
        title="Monitoring and detecting prohibited student behavior in examinations",
        obligation_articles=(
            "Art.6(2)+Annex III pt.3(d)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "exam proctoring AI",
            "online proctoring",
            "cheating detection AI",
            "plagiarism AI",
            "test monitoring AI",
            "student behavior monitoring exam",
        ),
        code_signals=(
            "proctoring",
            "proctor",
            "cheat_detection",
            "exam_monitor",
            "plagiarism_detect",
            "detect_cheating",
            "gaze_tracking_exam",
        ),
        excludes=(),
        subject_gated=True,
    ),
    # ── Area 4 — Employment ──────────────────────────────────────────────────
    AnnexIIIEntry(
        area=4,
        area_name="employment",
        subpoint="4(a)",
        title="Recruitment and selection: advertising, screening, evaluation",
        obligation_articles=(
            "Art.6(2)+Annex III pt.4(a)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "recruitment AI",
            "hiring algorithm",
            "resume screening AI",
            "CV screening",
            "candidate ranking",
            "job application filtering",
            "talent acquisition AI",
            "applicant tracking AI",
            "interview scoring AI",
            "Einstellungsentscheidung",
        ),
        code_signals=(
            "rank_candidates",
            "screen_resume",
            "screen_cv",
            "filter_applicants",
            "score_candidate",
            "hiring_model",
            "recruitment_model",
            "shortlist_candidates",
            "interview_score",
            "applicant_score",
            "ats_score",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=4,
        area_name="employment",
        subpoint="4(b)",
        title="Decisions affecting employment terms: promotion, termination, monitoring",
        obligation_articles=(
            "Art.6(2)+Annex III pt.4(b)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "employee performance AI",
            "worker monitoring AI",
            "performance evaluation AI",
            "promotion decision AI",
            "termination risk AI",
            "workforce analytics AI",
            "employee scoring",
            "productivity monitoring AI",
            "task allocation AI",
        ),
        code_signals=(
            "employee_score",
            "performance_score",
            "predict_attrition",
            "termination_risk",
            "promotion_model",
            "worker_monitor",
            "productivity_score",
            "task_allocate",
            "workforce_analytics",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    # ── Area 5 — Essential Services ──────────────────────────────────────────
    AnnexIIIEntry(
        area=5,
        area_name="essential_services",
        subpoint="5(a)",
        title="Public authority evaluating eligibility for public assistance benefits",
        obligation_articles=(
            "Art.6(2)+Annex III pt.5(a)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "public benefit eligibility AI",
            "social assistance AI",
            "welfare eligibility scoring",
            "benefit entitlement AI",
            "healthcare eligibility AI",
            "public service eligibility",
            "social security AI",
            "means testing AI",
        ),
        code_signals=(
            "eligibility_score",
            "benefit_eligibility",
            "welfare_score",
            "entitlement_check",
            "social_benefit",
            "means_test",
            "public_assistance",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=5,
        area_name="essential_services",
        subpoint="5(b)",
        title="Creditworthiness assessment and credit scoring",
        obligation_articles=(
            "Art.6(2)+Annex III pt.5(b)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "creditworthiness assessment",
            "credit scoring",
            "credit risk AI",
            "loan scoring",
            "credit decision AI",
            "retail credit AI",
            "mortgage scoring",
            "default probability",
            "credit risk model",
            "Kreditwürdigkeit",
            "credit underwriting",
            "lending decision AI",
            "FICO",
            "scorecard model",
        ),
        code_signals=(
            "credit_score",
            "creditworthiness",
            "predict_proba",
            "predict_default",
            "default_probability",
            "risk_score",
            "scorecard",
            "approve_loan",
            "loan_decision",
            "credit_risk",
            "underwriting_model",
            "lending_model",
            "fico_score",
            "credit_model",
        ),
        excludes=("fraud detection",),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=5,
        area_name="essential_services",
        subpoint="5(c)",
        title="Life insurance and health insurance risk assessment and pricing",
        obligation_articles=(
            "Art.6(2)+Annex III pt.5(c)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "insurance pricing AI",
            "health insurance risk AI",
            "life insurance AI",
            "actuarial AI model",
            "insurance underwriting AI",
            "premium calculation AI",
            "insurance risk scoring",
        ),
        code_signals=(
            "insurance_score",
            "predict_premium",
            "actuarial_model",
            "underwrite_policy",
            "insurance_risk",
            "premium_model",
            "health_risk_score",
            "life_risk_score",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=5,
        area_name="essential_services",
        subpoint="5(d)",
        title="Emergency dispatch and emergency call classification/prioritization",
        obligation_articles=(
            "Art.6(2)+Annex III pt.5(d)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "emergency dispatch AI",
            "911 triage AI",
            "112 dispatch AI",
            "emergency call classification",
            "emergency prioritization AI",
            "CAD AI",
            "computer aided dispatch",
            "first responder AI",
        ),
        code_signals=(
            "emergency_dispatch",
            "dispatch_priority",
            "call_classify",
            "triage_emergency",
            "cad_model",
            "incident_priority",
            "emergency_triage",
        ),
        excludes=(),
    ),
    # ── Area 6 — Law Enforcement ─────────────────────────────────────────────
    AnnexIIIEntry(
        area=6,
        area_name="law_enforcement",
        subpoint="6(a)",
        title="Individual risk assessment of becoming victim of criminal offenses",
        obligation_articles=(
            "Art.6(2)+Annex III pt.6(a)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "victimization risk AI",
            "victim risk assessment",
            "crime victim prediction",
            "vulnerability assessment AI",
        ),
        code_signals=(
            "victim_risk",
            "victimization_score",
            "crime_victim_predict",
            "vulnerability_score",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=6,
        area_name="law_enforcement",
        subpoint="6(b)",
        title="Polygraphs and tools assessing reliability of persons",
        obligation_articles=(
            "Art.6(2)+Annex III pt.6(b)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "polygraph AI",
            "lie detection AI",
            "deception detection AI",
            "statement credibility AI",
            "veracity assessment",
            "truthfulness scoring",
        ),
        code_signals=(
            "lie_detect",
            "deception_detect",
            "polygraph",
            "credibility_score",
            "veracity_score",
            "truthfulness_model",
        ),
        excludes=(),
    ),
    AnnexIIIEntry(
        area=6,
        area_name="law_enforcement",
        subpoint="6(c)",
        title="Evaluating reliability of evidence in criminal investigations",
        obligation_articles=(
            "Art.6(2)+Annex III pt.6(c)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "evidence reliability AI",
            "forensic evidence scoring",
            "evidence assessment AI",
            "criminal evidence AI",
        ),
        code_signals=(
            "evidence_reliability",
            "forensic_score",
            "evidence_assess",
            "criminal_evidence",
        ),
        excludes=(),
    ),
    AnnexIIIEntry(
        area=6,
        area_name="law_enforcement",
        subpoint="6(d)",
        title="Assessing risk of offending or reoffending, including recidivism",
        obligation_articles=(
            "Art.6(2)+Annex III pt.6(d)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "recidivism prediction",
            "reoffending risk AI",
            "offending risk assessment",
            "criminal risk score",
            "COMPAS",
            "actuarial risk tool",
            "pretrial risk assessment",
            "sentencing AI",
        ),
        code_signals=(
            "recidivism_score",
            "recidivism_predict",
            "reoffend_risk",
            "criminal_risk",
            "compas_score",
            "pretrial_risk",
            "sentencing_model",
            "offending_risk",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=6,
        area_name="law_enforcement",
        subpoint="6(e)",
        title="Profiling natural persons in criminal detection, investigation, or prosecution",
        obligation_articles=(
            "Art.6(2)+Annex III pt.6(e)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "criminal profiling AI",
            "suspect profiling",
            "offender profiling AI",
            "behavioral profiling law enforcement",
            "predictive policing",
        ),
        code_signals=(
            "criminal_profile",
            "suspect_score",
            "predictive_policing",
            "offender_profile",
            "behavioral_profile",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    # ── Area 7 — Migration, Asylum, Border Control ───────────────────────────
    AnnexIIIEntry(
        area=7,
        area_name="migration",
        subpoint="7(a)",
        title="Polygraph-like tools for migration/asylum/border authorities",
        obligation_articles=(
            "Art.6(2)+Annex III pt.7(a)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "border polygraph AI",
            "asylum credibility AI",
            "migration lie detection",
            "border deception detection",
        ),
        code_signals=(
            "border_deception",
            "asylum_credibility",
            "migration_polygraph",
        ),
        excludes=(),
    ),
    AnnexIIIEntry(
        area=7,
        area_name="migration",
        subpoint="7(b)",
        title="Assessing risk of persons entering or having entered EU territory",
        obligation_articles=(
            "Art.6(2)+Annex III pt.7(b)",
            "Art.9 risk mgmt",
            "Art.10 data governance",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "border risk assessment AI",
            "migration risk scoring",
            "irregular migration risk AI",
            "security risk traveler AI",
            "entry risk assessment",
        ),
        code_signals=(
            "border_risk",
            "migration_risk",
            "traveler_risk",
            "entry_risk",
            "security_risk_migration",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=7,
        area_name="migration",
        subpoint="7(c)",
        title="Assisting examination of asylum, visa, and residence permit applications",
        obligation_articles=(
            "Art.6(2)+Annex III pt.7(c)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "asylum application AI",
            "visa application AI",
            "residence permit AI",
            "immigration application scoring",
        ),
        code_signals=(
            "asylum_score",
            "visa_decision",
            "residence_permit",
            "immigration_score",
            "visa_score",
        ),
        excludes=(),
        art6_3_profiling=True,
        subject_gated=True,
    ),
    AnnexIIIEntry(
        area=7,
        area_name="migration",
        subpoint="7(d)",
        title="Detecting, recognizing, or identifying natural persons in border context",
        obligation_articles=(
            "Art.6(2)+Annex III pt.7(d)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "border identification AI",
            "person detection border",
            "automated border control",
            "ABC gate AI",
            "border biometrics",
        ),
        code_signals=(
            "border_detect",
            "border_identify",
            "abc_gate",
            "automated_border",
            "border_biometric",
        ),
        excludes=("verification of travel documents",),
        art6_3_profiling=True,
    ),
    # ── Area 8 — Justice & Democracy ─────────────────────────────────────────
    AnnexIIIEntry(
        area=8,
        area_name="justice_democracy",
        subpoint="8(a)",
        title="AI assisting judicial authorities in researching, interpreting, applying law",
        obligation_articles=(
            "Art.6(2)+Annex III pt.8(a)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "judicial AI",
            "legal interpretation AI",
            "court decision support AI",
            "legal outcome prediction",
            "judge decision AI",
            "case law AI",
            "legal research AI judicial",
        ),
        code_signals=(
            "judicial_decision",
            "court_ai",
            "legal_interpret",
            "judge_support",
            "case_outcome_predict",
            "judicial_support",
        ),
        excludes=(),
    ),
    AnnexIIIEntry(
        area=8,
        area_name="justice_democracy",
        subpoint="8(b)",
        title="AI intended to influence elections, referenda, or voting behavior",
        obligation_articles=(
            "Art.6(2)+Annex III pt.8(b)",
            "Art.9 risk mgmt",
            "Art.13 transparency",
            "Art.14 human oversight",
            "Art.43 conformity (self-assessment)",
            "Art.49 EU DB registration",
        ),
        conformity_path="self_assessment",
        keywords=(
            "election influence AI",
            "voter targeting AI",
            "voting behavior AI",
            "election manipulation AI",
            "political microtargeting AI",
            "referendum AI",
            "political advertising AI targeting",
        ),
        code_signals=(
            "voter_target",
            "election_model",
            "voting_predict",
            "political_target",
            "microtarget_voter",
            "referendum_influence",
        ),
        excludes=(),
    ),
]


def lookup_by_area(area: int) -> list[AnnexIIIEntry]:
    return [e for e in ANNEX_III if e.area == area]


def lookup_by_code_signal(token: str) -> list[AnnexIIIEntry]:
    from opencomplai_core.scanner.detectors._signals import match_code_signal

    return [
        e
        for e in ANNEX_III
        if any(match_code_signal(token, sig) for sig in e.code_signals)
    ]


def lookup_by_keyword(text: str) -> list[AnnexIIIEntry]:
    text_lower = text.lower()
    return [e for e in ANNEX_III if any(kw in text_lower for kw in e.keywords)]


def all_code_signals() -> set[str]:
    result: set[str] = set()
    for entry in ANNEX_III:
        result.update(entry.code_signals)
    return result


def all_keywords() -> set[str]:
    result: set[str] = set()
    for entry in ANNEX_III:
        result.update(entry.keywords)
    return result
